name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub (optional, for pushing images)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t kxlsxconverterapi:latest .

    # Push the Docker image (optional)
    - name: Push Docker image
      run: |
        docker tag kxlsxconverterapi:latest ${{ secrets.DOCKER_USERNAME }}/kxlsxconverterapi:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/kxlsxconverterapi:latest
